Admin Manage Accounts Tab
TritonSE/WA-Family-Literacy-Application pull request #38
Opened 2021-05-19 00:02 UTC by aksharans

### Administrative Info
Monday Board ID: 853642866
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Manage accounts page with ability to add, delete, and edit admins
- Admin card component
- add admin routes to api

### Testing
How did you confirm your changes worked? 
- Tested adding, deleting, editing admins with backend locally, and with test data

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
- cd web, npm start
- cd backend, make, DISABLE_AUTH=true ./words-alive
- curl -H "Authorization: Bearer test-token-1" localhost:8080/admins

2021-05-19 07:31 UTC, dacruz21 requested changes
Ik you're still working on the checkboxes so no comment there :)

Looks fantastic, thanks for putting this together so quickly and cleanly. Just a few comments:

2021-05-19 07:31 UTC, dacruz21 commented on web/src/App.css
> +.h1 {
Can you plz re-indent this file consistently?

2021-05-19 07:31 UTC, dacruz21 commented on web/src/api/WordsAliveAPI.tsx
> +  // make & DISABLE_AUTH=true ./words-alive
Go ahead and remove this now, we'll do this properly in the login site PR

2021-05-19 07:31 UTC, dacruz21 commented on web/src/api/WordsAliveAPI.tsx
> +  // make & DISABLE_AUTH=true ./words-alive
(and remove the notes to self :slightly_smiling_face: )

2021-05-19 07:31 UTC, dacruz21 commented on web/src/pages/ManageAccountsPage.module.css
> +}
Sorry, only class selectors in module files please

2021-05-19 07:31 UTC, dacruz21 commented on web/src/pages/ManageAccountsPage.module.css
> +}
Same here, you can define a class for these inputs or use a child selector on another class

2021-05-19 07:31 UTC, dacruz21 commented on web/src/pages/ManageAccountsPage.tsx
> +const test: Admin[] = [
Remove plz

2021-05-19 07:31 UTC, dacruz21 commented on web/src/components/AdminCard.module.css
> +    height: 80%;
Can you remove the height:80% please? It looks funny on my screen but it looks totally fine if we just let it shrinkwrap.

2021-05-19 19:02 UTC, aksharans commented
Made the custom checkboxes similar to the upload books page (without an image). If everything looks good, I can go ahead and delete the WordsAliveAPI stuff and push again.
Also, I saw a type selector in UploadBooksPage.module.css, but I didn't have the updated version so I wasn't able to fix it in this branch

2021-05-19 19:06 UTC, dacruz21 commented
Looks good, can you try to line these labels up though?

![image](https://user-images.githubusercontent.com/36964941/118869689-90dfea00-b89a-11eb-8342-4f7e4f59cba0.png)

2021-05-19 19:08 UTC, aksharans commented
By line up, did you mean have everything left-aligned?

2021-05-19 19:13 UTC, dacruz21 commented
Yeah, I think it would look best if we left align the text and right align the check boxes

2021-05-19 19:50 UTC, dacruz21 submitted a review, later dismissed
LGTM, great work. Please ping someone else for review.

2021-05-20 21:44 UTC, dacruz21 approved these changes, later dismissed

2021-05-20 21:45 UTC, dacruz21 submitted a review, later dismissed

2021-05-22 00:19 UTC, allisonbhavsar requested changes
Minor style fix but other than that looks and works great! Are we leaving the error messages as alerts?

2021-05-22 00:19 UTC, allisonbhavsar commented on web/src/pages/ManageAccountsPage.module.css
> +    margin-left: 12px;
Any reason for the left margin here? In the mockup the title looks aligned all the way to the left

2021-05-22 04:29 UTC, dacruz21 approved these changes

2021-05-22 04:29 UTC, aksharans commented
Removed the margin left and I believe the errors messages would be alerts, @dacruz21 ?

2021-05-22 04:30 UTC, dacruz21 commented
Yeah alerts are probably fine for now, I can ask design their thoughts

2021-05-22 16:05 UTC, allisonbhavsar approved these changes
LGTM

2021-05-22 16:05 UTC, merged