Forgot Password Flow (w/PopUp Modal & KeyboardAvoidingView)
TritonSE/WA-Family-Literacy-Application pull request #52
Opened 2021-10-14 03:29 UTC by aksharans

### Administrative Info
Monday Board ID: 853642866
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- AuthContext: implemented setPasswordResetEmail()
- ForgotPasswordScreeen: text input to send password reset email, with error handling and popup modal on success
- PopUpModal: modal to indicate success and navigate to previous screen in stack
- LoginScreen & SignUpScreen: added KeyboardAvoidingView

-included some commented code, but can remove before merging

### Testing
How did you confirm your changes worked? 
- ran on staging server, added valid & invalid emails and successfully signed in with resetted pswd

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
npm run staging, click Forgot Password in Sign In Screen, valid emails in firebase

2021-10-18 23:32 UTC, dacruz21 requested changes
Great work, thank you both!!

Some thoughts:
* I wasn't able to get a good `npm install` on your branch, JS rot lol. I opened PR #53 to fix the install errors. CI seems happy for some reason so we can land these in either order
* KeyboardAvoidingView still doesn't work on Android :( Oh well, if it works on iOS it's definitely better than nothing, thanks for making the change
* Let's add some explanation text to the reset password form, something like "Enter the email address you used when creating your account to receive instructions for resetting your password", idk something like that. Then we can just change the "Send Email to Reset Password" button to just Reset or Send or something
* You can add a prop on the TextInput to specify that the expected value is an email address - this is pretty useful as it changes the layout of the keyboard on the device, moves the @ sign to the main keyboard, adds autofills for gmail.com, yahoo.com, etc.
* I like the modal :D

2021-10-18 23:32 UTC, dacruz21 commented on mobile/src/context/AuthContext.tsx
> +// import { Alert } from 'react-native';
remove comments please

2021-10-18 23:32 UTC, dacruz21 commented on mobile/src/context/AuthContext.tsx
> +  */
^

2021-10-18 23:32 UTC, dacruz21 commented on mobile/src/context/AuthContext.tsx
> +          setError(new Error('User With Email Does Not Exist'));
How about "Could not find an account with that email address"?

2021-10-20 20:21 UTC, dacruz21 approved these changes
Updated the wording after talking to Robyn today, LGTM!

2021-10-21 17:29 UTC, petabite approved these changes
LGTM! Left some small suggestions below if you want to add them in.

2021-10-21 17:29 UTC, petabite commented on mobile/src/screens/login/LoginScreen.tsx
> +              <Text style={styles.forgotPasswordText}>{i18n.t('forgotPassword')} </Text>
Maybe change the double quotes to single quotes (also in a couple of other places). I believe David is working on the linter though, so probably not a big issue.

2021-10-21 17:29 UTC, petabite commented on mobile/src/screens/login/ForgotPasswordScreen.tsx
> +          <TextInput style={[styles.input, TextStyles.caption3]} value={email} onChangeText={setEmail} placeholder={i18n.t('email')} placeholderTextColor={Colors.gray} textContentType="emailAddress"
```suggestion
          <TextInput style={[styles.input, TextStyles.caption3]} value={email} onChangeText={setEmail} placeholder={i18n.t('email')} placeholderTextColor={Colors.gray} textContentType="emailAddress" keyboardType="email-address" autoCapitalize='none'/>
```
Super small UX issue - I noticed that the email input automatically capitalizes the first character, which is a little weird. Adding this should fix that.

2021-10-21 21:01 UTC, merged