Feature/allisonbhavsar/1754809889 extra analytics api routes
TritonSE/WA-Family-Literacy-Application pull request #58
Opened 2021-11-03 00:51 UTC by allisonbhavsar

### Administrative Info
Monday Board ID: 853642866
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added /analytics?range=<days> api for getting all book analytics in the past <days> days
- Added /books/popular for getting 5 most popular books in the past 30 days
- Created a separate function for determining what indices to use when slicing into the analytics clicks array

### Testing
How did you confirm your changes worked? 
- Unit tests

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

- curl -H "Authorization: Bearer test-token-primary" localhost:8080/analytics?range=1
- curl -H "Authorization: Bearer test-token-primary" localhost:8080/books/popular

2021-11-03 03:55 UTC, dacruz21 requested changes
Great work, this definitely works well but I think the analytics queries are starting to get messy. DMed you some ideas for refactoring and left some comments below. Let me know your thoughts, these are definitely tricky queries!

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +func AnalyticsClicksIndices(dRange int) (int, int, int) {
I think this logic can be moved into SQL pretty easily with the expression I DMed you both.

`clicks[366-30+TODAY:] || clicks[TODAY-30:TODAY]` will always select the last 30 days with wraparound (as far as I can tell)

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +		"FROM book_analytics WHERE id = $4"
IMO remove AnalyticsClickIndices call, replace with `clicks[366-dRange+today:] || clicks[today-dRange:today]`. You can get the value for today from YearDay() in Go, no need to try and generate it in SQL. Also maybe we should rename dRange to numDays?

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +	var query string = "SELECT id, ARRAY_CAT(clicks[$1:$2], clicks[1:$3]) " +
Can be done without AnalyticsClicksIndices

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +func (db *BookDatabase) FetchPopularBooks(ctx context.Context) ([]models.Book, error) {
This function should use the book_analytics_last_30 view IMO, basically select the top 5 from that table (using the `total` column) and join it with `books`.

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +		"book_contents.id LEFT JOIN book_analytics ON books.id = book_analytics.id " +
You shouldn't need to join with book_contents here since we aren't returning any of the read/explore/learn data.

2021-11-03 03:55 UTC, dacruz21 commented on backend/internal/database/book.go
> +		"DESC FETCH FIRST 5 ROWS ONLY"
huh I didn't know `FETCH FIRST 5 ROWS ONLY` was valid SQL, is it the same as `LIMIT 5` or is it different?

2021-11-17 20:29 UTC, dacruz21 approved these changes, later dismissed

2021-11-19 02:36 UTC, dacruz21 approved these changes

2021-11-19 19:26 UTC, petabite approved these changes
👌

2021-11-19 20:37 UTC, merged