Feature/dhrvsood/939326603 main app nav
TritonSE/WA-Family-Literacy-Application pull request #8
Opened 2021-02-02 03:04 UTC by allisonbhavsar

### Administrative Info
Monday Board ID: 853642866
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Set up routing using React Navigation
- Created bottom menu linking to Home, Chat, and Settings Screens

### Testing
How did you confirm your changes worked? 
- Navbar rendered and routed properly on two different devices

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![IMG_CF7984FB0146-1](https://user-images.githubusercontent.com/47436434/106546406-fb257800-64bf-11eb-91a7-8b37a56e142d.jpeg)

2021-02-02 20:49 UTC, dacruz21 requested changes
Nice! Let's just clean up the logic for the tab navigator and a few other minor things. Also, can you put comments on the 3 screens? Just something very brief, like "Left tab on home screen for chatting with volunteers".

2021-02-02 20:49 UTC, dacruz21 commented on mobile/App.tsx
> +            let height;
Let's define these styles in the style sheet below, just to keep things a little cleaner.

2021-02-02 20:49 UTC, dacruz21 commented on mobile/App.tsx
> +            return <Image style={{ width: width, height: height, tintColor: tint }} source={icon} />;
Also this is kinda messy. How about a map that you can index into with `route.name`? like:

```ts
const TabIcons = {
  Home: <Image style={styles.homeTabIcon} source={require('./assets/images/Home.png')} />,
  ...
};
```

```ts
screenOptions = {({ route }) => ({
  tabBarIcon: () => TabIcons[route.name]
)}
```

2021-02-02 20:49 UTC, dacruz21 commented on mobile/package.json
> +    "react-native-svg-transformer": "^0.14.3",
Just checking... are all of these needed? At the very least I don't think we need the svg libs now that we're using PNGs, right? (also if you remove any remember to `npm install` again so the package lock gets updated)

2021-02-02 20:49 UTC, dacruz21 commented on mobile/src/screens/ChatScreen.tsx
> +};
Super minor thing but can you just add a quick stylesheet so the view is centered in the screen (like the original TODO in App.tsx)? Same with Home and Settings

2021-02-02 20:49 UTC, dacruz21 commented on mobile/src/screens/Settings.tsx
> +export const Settings: React.FC = () => {
I like the convention of ending each screen with `Screen`, can you add that here?

2021-02-04 23:42 UTC, dacruz21 approved these changes
![lgtm](https://i.imgur.com/xvWUf09.png)

2021-02-05 00:25 UTC, RohithKasar approved these changes
Code base looks clean. Ran it on my phone and was able to switch through the 3 navigation items at the bottom. Colors and highlighting are nice!

looks good to me

2021-02-05 00:58 UTC, merged